"""Add date access.

Revision ID: b5c4c0da806b
Revises: 
Create Date: 2024-01-09 03:58:29.389484

"""
from alembic import op
import sqlalchemy as sa
import datetime

# revision identifiers, used by Alembic.
revision = 'b5c4c0da806b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartogram_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_accessed', sa.DateTime(), nullable=True, server_default='0001-01-01 00:00:00'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartogram_entry', schema=None) as batch_op:
        batch_op.drop_column('date_accessed')

    # ### end Alembic commands ###
