"""Add title

Revision ID: dc3e0231c0a7
Revises: 
Create Date: 2024-11-15 00:58:44.219591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3e0231c0a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartogram_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartogram_entry', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
