"""Initial migration

Revision ID: dc3e0231c0a7
Revises:
Create Date: 2024-11-15 00:58:44.219591

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dc3e0231c0a7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cartogram_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("string_key", sa.String(length=32), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.Column(
            "date_accessed",
            sa.DateTime(),
            server_default="0001-01-01 00:00:00",
            nullable=True,
        ),
        sa.Column("handler", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("string_key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cartogram_entry")
    # ### end Alembic commands ###
