cartogram_handlers = {
    "argentina": {"name": "Argentina"},
    "australia": {"name": "Australia", "hidden": True},
    "canada": {"name": "Canada"},
    "japan2": {"name": "Japan", "hidden": True},
    "france": {"name": "France", "hidden": True},
    "uae": {"name": "United Arab Emirates"},
    "asean": {"name": "ASEAN Countries"},
    "mexico": {"name": "Mexico"},
    "singaporePA": {"name": "Singapore (by Planning Area)", "hidden": True},
    "saudiArabia": {"name": "Saudi Arabia"},
    "netherlands": {"name": "Netherlands"},
    "thailand": {"name": "Thailand"},
    "phl": {"name": "Philippines"},
    "israel3": {"name": "Israel"},
    "vietnam": {"name": "Vietnam", "hidden": True},
    "southAfrica": {"name": "South Africa"},
    "italy2": {"name": "Italy"},
    "colombia": {"name": "Colombia"},
    "southKorea2": {"name": "South Korea"},
    "newZealand": {"name": "New Zealand"},
    "europe": {"name": "Europe (Eurostat members)"},
    "algeria": {"name": "Algeria", "hidden": True},
    "libya": {"name": "Libya"},
    "switzerland": {"name": "Switzerland", "hidden": True},
    "ireland": {"name": "Ireland"},
    "poland": {"name": "Poland"},
    "sweden": {"name": "Sweden"},
    "croatia": {"name": "Croatia", "hidden": True},
    "czechrepublic3": {"name": "Czech Republic"},
    "hungary": {"name": "Hungary"},
    "unitedkingdom2": {"name": "United Kingdom"},
    "finland": {"name": "Finland"},
    "austria": {"name": "Austria", "hidden": True},
    "denmark": {"name": "Denmark"},
    "belgium": {"name": "Belgium", "hidden": True},
    "nigeria": {"name": "Nigeria"},
    "russia": {"name": "Russia", "hidden": True},
    "luxembourg": {"name": "Luxembourg"},
    "bangladesh": {"name": "Bangladesh"},
    "sanMarino": {"name": "San Marino"},
    "portugal": {"name": "Portugal"},
    "greece": {"name": "Greece"},
    "malaysia": {"name": "Malaysia", "hidden": True},
    "qatar": {"name": "Qatar"},
    "turkey": {"name": "Turkey"},
    "cambodia": {"name": "Cambodia"},
    "andorra": {"name": "Andorra"},
    "ethiopia": {"name": "Ethiopia"},
    "myanmar": {"name": "Myanmar"},
    "chile": {"name": "Chile"},
    "kaz": {"name": "Kazakhstan"},
    "sudan": {"name": "Sudan"},
    "mongolia": {"name": "Mongolia"},
    "peru": {"name": "Peru"},
    "pak": {"name": "Pakistan"},
    "bolivia": {"name": "Bolivia"},
    "iceland": {"name": "Iceland"},
    "domrep": {"name": "Dominican Republic"},
    "laos": {"name": "Laos"},
    "paraguay": {"name": "Paraguay"},
    "nepal": {"name": "Nepal"},
    "angola": {"name": "Angola"},
    "romania": {"name": "Romania"},
    "ukraine": {"name": "Ukraine"},
    "jamaica": {"name": "Jamaica"},
    "yemen": {"name": "Yemen"},
    "belarus": {"name": "Belarus"},
    "bahamas": {"name": "The Bahamas", "hidden": True},
    "guyana": {"name": "Guyana"},
    "washington": {"name": "Washington (U.S. State)"},
    "lebanon": {"name": "Lebanon"},
    "spain5": {"name": "Spain"},
    "arab_league": {"name": "Arab League"},
    "estonia": {"name": "Estonia"},
    "usa": {"name": "United States (Conterminous)", "hidden": True},
    "brazil": {"name": "Brazil", "hidden": True},
    "china": {"name": "China (Mainland China and Taiwan)", "hidden": True},
    "china2": {"name": "Taiwan (Mainland China and Taiwan)", "hidden": True},
    "india": {"name": "India"},
    "srilanka": {"name": "Sri Lanka"},
    "germany": {"name": "Germany", "hidden": True},
    "singaporeRe": {"name": "Singapore (by Region)"},
    "indonesia": {"name": "Indonesia", "hidden": True},
    "world": {"name": "World", "hidden": True},
    "usa-home-demo": {
        "hidden": True,
        "name": "United States",
        "types": {
            "[Contiguous] Population (people)": "contiguous",
            "[Noncontiguous] Population (people)": "noncontiguous",
            "Population Density (per sq. km)": "choropleth",
        },
        "settings": {
            "isAdvanceMode": False,
            "scheme": "blues",
            "type": "quantile",
            "step": 5,
            "spec": {
                "scales": [
                    {
                        "name": "Population Density (per sq. km)",
                        "type": "quantile",
                        "domain": {
                            "data": "source_csv",
                            "field": "Population Density (per sq. km)",
                        },
                        "range": {"scheme": "blues", "count": 5},
                    }
                ],
                "legend_titles": {
                    "Population Density (per sq. km)": "Population Density (per sq. km, quintiles)"
                },
            },
        },
    },
    "algeria_by_wilaya_since_2019": {
        "name": "Algeria",
        "types": {"Population (people)": "contiguous"},
    },
    "australia_by_state_and_territory_since_1942": {
        "name": "Australia",
        "types": {"Population (people)": "contiguous"},
    },
    "austria_by_state_since_1945": {
        "name": "Austria",
        "types": {"Population (people)": "contiguous"},
    },
    "bahamas_by_district_since_1999": {
        "name": "Bahamas, the",
        "types": {"Population (people)": "contiguous"},
    },
    "belgium_by_region_simplified_since_1995": {
        "name": "belgium_by_region_simplified_since_1995",
        "hidden": True,
        "types": {"Population (people)": "contiguous"},
    },
    "belgium_by_region_since_1995": {
        "name": "Belgium",
        "types": {"Population (people)": "contiguous"},
    },
    "brazil_by_state_since_1988": {
        "name": "Brazil",
        "types": {"Population (people)": "contiguous"},
    },
    "china_by_province_with_chinese_taipei_since_1998": {
        "name": "China (Mainland China and Taiwan)",
        "types": {"Population (people)": "contiguous"},
    },
    "conterminous_usa_by_state_since_1959": {
        "name": "United States (Conterminous)",
        "types": {"Population (people)": "contiguous"},
    },
    "contiguous_usa_by_county_since_2001": {
        "name": "United States (Contiguous)",
        "types": {"Population (people)": "contiguous"},
    },
    "croatia_by_county_since_1992": {
        "name": "Croatia",
        "types": {
            "Population (people)": "contiguous",
            "Covid Cases (cases)": "contiguous",
        },
    },
    "egypt_by_governorate_since_2009": {
        "name": "Egypt",
        "types": {"Population (people)": "contiguous"},
    },
    "england_by_region_since_2023": {
        "name": "England",
        "types": {"Population (people)": "contiguous"},
    },
    "eu_by_country_until_2020": {
        "name": "European Union (by Country)",
        "types": {"Population (people)": "contiguous"},
    },
    "eu_by_region_until_2020": {
        "name": "European Union (by Region)",
        "types": {"Population (people)": "contiguous"},
    },
    "france_by_metropolitan_region_since_2016": {
        "name": "France (by Metropolitan Region)",
        "types": {"Population (people)": "contiguous"},
    },
    "germany_by_state_since_1990": {
        "name": "Germany",
        "types": {"Population (people)": "contiguous"},
    },
    "indonesia_by_province_since_2022": {
        "name": "Indonesia",
        "types": {"Population (people)": "contiguous"},
    },
    "japan_by_prefecture_since_1888": {
        "name": "Japan",
        "types": {"Population (people)": "contiguous"},
    },
    "malaysia_by_state_since_2001": {
        "name": "Malaysia",
        "types": {"Population (people)": "contiguous"},
    },
    "metropolitan_france_by_departement_since_2015": {
        "name": "France (by Departement)",
        "types": {"Population (people)": "contiguous"},
    },
    "russia_by_federal_subject_since_2008": {
        "name": "Russia",
        "types": {"Population (people)": "contiguous"},
    },
    "singapore_by_planning_area_since_1999": {
        "name": "Singapore (by Planning Area)",
        "types": {"Population (people)": "contiguous"},
    },
    "switzerland_by_canton_since_1999": {
        "name": "Switzerland",
        "types": {
            "Population (people)": "contiguous",
            "GDP (billion chf)": "contiguous",
        },
    },
    "tunisia_by_governorate_since_1994": {
        "name": "Tunisia",
        "types": {"Population (people)": "contiguous"},
    },
    "usa_by_state_since_1959": {
        "name": "United States",
        "types": {"Population (people)": "contiguous"},
    },
    "vietnam_by_province_since_1996": {
        "name": "Vietnam",
        "types": {"Population (people)": "contiguous"},
    },
    "world_by_region": {
        "name": "World (by Region)",
        "types": {"Population (people)": "contiguous"},
    },
    "world_by_region_wo_antarctica": {
        "name": "World (by Region without Antarctica)",
        "types": {"Population (people)": "contiguous"},
    },
    "world_by_country_since_2022": {
        "name": "World (by Country)",
        "types": {"Population (people)": "contiguous"},
    },
}
