cartogram_handlers = {
    "argentina": {"name": "Argentina"},
    "australia": {"name": "Australia"},
    "canada": {"name": "Canada"},
    "japan2": {"name": "Japan"},
    "france": {"name": "France"},
    "uae": {"name": "United Arab Emirates"},
    "asean": {"name": "ASEAN Countries"},
    "mexico": {"name": "Mexico"},
    "singaporePA": {"name": "Singapore (by Planning Area)"},
    "saudiArabia": {"name": "Saudi Arabia"},
    "netherlands": {"name": "Netherlands"},
    "thailand": {"name": "Thailand"},
    "phl": {"name": "Philippines"},
    "israel3": {"name": "Israel"},
    "vietnam": {"name": "Vietnam"},
    "southAfrica": {"name": "South Africa"},
    "italy2": {"name": "Italy"},
    "colombia": {"name": "Colombia"},
    "southKorea2": {"name": "South Korea"},
    "newZealand": {"name": "New Zealand"},
    "europe": {"name": "Europe (Eurostat members)"},
    "algeria": {"name": "Algeria"},
    "libya": {"name": "Libya"},
    "switzerland": {"name": "Switzerland"},
    "ireland": {"name": "Ireland"},
    "poland": {"name": "Poland"},
    "sweden": {"name": "Sweden"},
    "croatia": {"name": "Croatia"},
    "czechrepublic3": {"name": "Czech Republic"},
    "hungary": {"name": "Hungary"},
    "unitedkingdom2": {"name": "United Kingdom"},
    "finland": {"name": "Finland"},
    "austria": {"name": "Austria"},
    "denmark": {"name": "Denmark"},
    "belgium": {"name": "Belgium"},
    "nigeria": {"name": "Nigeria"},
    "russia": {"name": "Russia"},
    "luxembourg": {"name": "Luxembourg"},
    "bangladesh": {"name": "Bangladesh"},
    "sanMarino": {"name": "San Marino"},
    "portugal": {"name": "Portugal"},
    "greece": {"name": "Greece"},
    "malaysia": {"name": "Malaysia"},
    "qatar": {"name": "Qatar"},
    "turkey": {"name": "Turkey"},
    "cambodia": {"name": "Cambodia"},
    "andorra": {"name": "Andorra"},
    "ethiopia": {"name": "Ethiopia"},
    "myanmar": {"name": "Myanmar"},
    "chile": {"name": "Chile"},
    "kaz": {"name": "Kazakhstan"},
    "sudan": {"name": "Sudan"},
    "mongolia": {"name": "Mongolia"},
    "peru": {"name": "Peru"},
    "pak": {"name": "Pakistan"},
    "bolivia": {"name": "Bolivia"},
    "iceland": {"name": "Iceland"},
    "domrep": {"name": "Dominican Republic"},
    "laos": {"name": "Laos"},
    "paraguay": {"name": "Paraguay"},
    "nepal": {"name": "Nepal"},
    "angola": {"name": "Angola"},
    "romania": {"name": "Romania"},
    "ukraine": {"name": "Ukraine"},
    "jamaica": {"name": "Jamaica"},
    "yemen": {"name": "Yemen"},
    "belarus": {"name": "Belarus"},
    "bahamas": {"name": "The Bahamas"},
    "guyana": {"name": "Guyana"},
    "washington": {"name": "Washington (U.S. State)"},
    "lebanon": {"name": "Lebanon"},
    "spain5": {"name": "Spain"},
    "arab_league": {"name": "Arab League"},
    "estonia": {"name": "Estonia"},
    "usa": {"name": "United States (Conterminous)"},
    "brazil": {"name": "Brazil"},
    "china": {"name": "China (Mainland China and Taiwan)"},
    "china2": {"name": "Taiwan (Mainland China and Taiwan)"},
    "india": {"name": "India"},
    "srilanka": {"name": "Sri Lanka"},
    "germany": {"name": "Germany"},
    "singaporeRe": {"name": "Singapore (by Region)"},
    "indonesia": {"name": "Indonesia"},
    "world": {"name": "World"},
    "usa-home-demo": {
        "hidden": True,
        "name": "United States",
        "types": {
            "[Contiguous] Population (people)": "contiguous",
            "[Noncontiguous] Population (people)": "noncontiguous",
            "Population Density (per sq. km)": "choropleth",
        },
        "settings": {
            "isAdvanceMode": False,
            "scheme": "blues",
            "type": "quantile",
            "step": 5,
            "spec": {
                "scales": [
                    {
                        "name": "Population Density (per sq. km)",
                        "type": "quantile",
                        "domain": {
                            "data": "source_csv",
                            "field": "Population Density (per sq. km)",
                        },
                        "range": {"scheme": "blues", "count": 5},
                    }
                ],
                "legend_titles": {
                    "Population Density (per sq. km)": "Population Density (per sq. km, quintiles)"
                },
            },
        },
    },
}
